Feature/ogisvc 818 poc azure ad
optinf/liferay-oidc-plugin pull request #1
Opened 2019-05-22 19:04 UTC by greiko

2019-07-17 14:17 UTC, lehoule requested changes

2019-07-17 14:17 UTC, lehoule commented on oidc-hook/src/main/java/nl/finalist/liferay/oidc/Liferay62Adapter.java
> +                UserLocalServiceUtil.addUserGroupUser(id, user);
Si l'utilisateur est déjà dans le groupe ça ne plante pas et ça n'empêche pas le reste de se mettre à jour?

Tu catch les exceptions juste avec un log...

2019-07-19 20:55 UTC, greiko commented on oidc-hook/src/main/java/nl/finalist/liferay/oidc/Liferay62Adapter.java
> +                UserLocalServiceUtil.addUserGroupUser(id, user);
J'ai ajouté un throw et j'ai aussi fixed la gestion de l'utilisateur aussi

2019-07-22 13:05 UTC, lehoule approved these changes

2019-07-22 13:06 UTC, merged